# Generated by Django 4.1.2 on 2022-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="driver_detail",
            fields=[
                ("driver_id", models.AutoField(primary_key=True, serialize=False)),
                ("d_fname", models.CharField(max_length=50)),
                ("d_lname", models.CharField(max_length=50)),
                ("d_email", models.EmailField(max_length=50)),
                ("d_phone", models.CharField(max_length=15)),
                ("d_password", models.CharField(max_length=50)),
                ("gender", models.CharField(max_length=10)),
                ("d_photo", models.CharField(max_length=100)),
                ("D_firebaseid", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                ("age", models.CharField(max_length=5)),
                ("gender", models.CharField(max_length=10)),
                ("Firebase_id", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(name="user_details",),
    ]
