# Generated by Django 4.1.2 on 2022-11-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_driver_detail_users_delete_user_details"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
