# Generated by Django 4.1.2 on 2022-11-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0004_alter_driver_detail_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users", name="email", field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="users", name="fname", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="users", name="lname", field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="users", name="password", field=models.CharField(max_length=200),
        ),
    ]
