# Generated by Django 4.1.2 on 2022-11-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0005_alter_users_email_alter_users_fname_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="driver_detail", options={},),
        migrations.AlterModelOptions(name="users", options={},),
    ]
