# Generated by Django 4.1.2 on 2022-11-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0006_alter_driver_detail_options_alter_users_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
