# Generated by Django 4.1.2 on 2022-11-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0007_alter_users_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver_detail",
            options={"verbose_name": "driver", "verbose_name_plural": "drivers"},
        ),
    ]
