# Generated by Django 4.1.2 on 2022-11-21 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0010_alter_driver_detail_d_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(name="driver_detail", options={},),
        migrations.AlterModelOptions(name="users", options={},),
    ]
