# Generated by Django 4.1.2 on 2022-11-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0011_alter_driver_detail_options_alter_users_options"),
    ]

    operations = [
        migrations.RemoveField(model_name="driver_detail", name="D_firebaseid",),
        migrations.RemoveField(model_name="users", name="Firebase_id",),
    ]
