# Generated by Django 4.1.2 on 2022-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0012_remove_driver_detail_d_firebaseid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver_detail",
            name="d_photo",
            field=models.ImageField(upload_to="images"),
        ),
    ]
