# Generated by Django 4.1.2 on 2023-02-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0013_alter_driver_detail_d_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver_detail", old_name="d_fname", new_name="d_name",
        ),
        migrations.RemoveField(model_name="driver_detail", name="d_lname",),
        migrations.AlterField(
            model_name="driver_detail",
            name="d_photo",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="driversphoto"
            ),
        ),
    ]
