# Generated by Django 4.1.2 on 2023-02-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0014_rename_d_fname_driver_detail_d_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver_detail",
            name="d_photo",
            field=models.ImageField(
                blank=True,
                default="images/None/No0img.jpg",
                max_length=255,
                null=True,
                upload_to="driversphoto",
            ),
        ),
    ]
