# Generated by Django 4.1.2 on 2023-02-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0015_alter_driver_detail_d_photo"),
    ]

    operations = [
        migrations.RenameField(model_name="users", old_name="fname", new_name="name",),
        migrations.RemoveField(model_name="users", name="lname",),
    ]
